using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using GestionObra.Dominio;
using GestionObra.Dominio.Entidades;
using GestionObra.Interfaces.AsistenciaContratista.DTOs;
using GestionObra.Interfaces.AsistenciaDiaria.DTOs;
using GestionObra.Interfaces.Banco.DTOs;
using GestionObra.Interfaces.Caja.DTOs;
using GestionObra.Interfaces.Categoria.DTOs;
using GestionObra.Interfaces.Causa.DTOs;
using GestionObra.Interfaces.ChequeEntrada.DTOs;
using GestionObra.Interfaces.ChequeSalida.DTOs;
using GestionObra.Interfaces.ComprobanteCompra.DTOs;
using GestionObra.Interfaces.ComprobanteEntrada.DTOs;
using GestionObra.Interfaces.ComprobanteSalida.DTOs;
using GestionObra.Interfaces.CondicionIva.DTOs;
using GestionObra.Interfaces.Contratista.DTOs;
using GestionObra.Interfaces.CuentaCorriente.DTOs;
using GestionObra.Interfaces.Deposito.DTOs;
using GestionObra.Interfaces.DescripcionTarea.DTOs;
using GestionObra.Interfaces.DetalleCaja.DTOs;
using GestionObra.Interfaces.DetalleComprobante.DTOs;
using GestionObra.Interfaces.Empleado.DTOs;
using GestionObra.Interfaces.Empresa.DTOs;
using GestionObra.Interfaces.FormaPago.DTOs;
using GestionObra.Interfaces.Gasto.DTOs;
using GestionObra.Interfaces.Identificacion.DTOs;
using GestionObra.Interfaces.IngresoMaterial.DTOs;
using GestionObra.Interfaces.Jornal.DTOs;
using GestionObra.Interfaces.Material.DTOs;
using GestionObra.Interfaces.Movimiento.DTOs;
using GestionObra.Interfaces.Obra.DTOs;
using GestionObra.Interfaces.Operacion.DTOs;
using GestionObra.Interfaces.Precio.DTOs;
using GestionObra.Interfaces.Presupuesto.DTOs;
using GestionObra.Interfaces.Proveedor.DTOs;
using GestionObra.Interfaces.Rubro.DTOs;
using GestionObra.Interfaces.SalarioMinimo.DTOs;
using GestionObra.Interfaces.SalidaMaterial.DTOs;
using GestionObra.Interfaces.Stock.DTOs;
using GestionObra.Interfaces.SubRubro.DTOs;
using GestionObra.Interfaces.Tarea.DTOs;
using GestionObra.Interfaces.TipoGasto.DTOs;
using GestionObra.Interfaces.Transferencia.DTOs;
using GestionObra.Interfaces.Usuario.DTOs;
using GestionObra.Interfaces.Zona.DTOs;

namespace MapperProfile
{
    public class MapperProfile : Profile
    {
        public MapperProfile()
        {
            CreateMap<AsistenciaContratistaDto, AsistenciaContratista>().ReverseMap();
            CreateMap<AsistenciaDiariaDto, AsistenciaDiaria>().ReverseMap();
            CreateMap<BancoDto, Banco>().ReverseMap();
            CreateMap<CausaFaltaDto, CausaFalta>().ReverseMap();
            CreateMap<CajaDto, Caja>().ReverseMap();
            CreateMap<CategoriaDto, Categoria>().ReverseMap();
            CreateMap<ContratistaDto, Contratista>().ReverseMap();
            CreateMap<ComprobanteCompraDto, ComprobanteCompra>().ReverseMap();
            CreateMap<ChequeEntradaDto, ChequeEntrada>().ReverseMap();
            CreateMap<ChequeSalidaDto, ChequeSalida>().ReverseMap();
            CreateMap<ComprobanteEntradaDto, ComprobanteEntrada>().ReverseMap();
            CreateMap<ComprobanteSalidaDto, ComprobanteSalida>().ReverseMap();
            CreateMap<CondicionIvaDto, CondicionIva>().ReverseMap();
            CreateMap<IdentificacionDto, Identificacion>().ReverseMap();
            CreateMap<CuentaCorrienteDto, CuentaCorriente>().ReverseMap();
            CreateMap<DescripcionTareaDto, DescripcionTarea>().ReverseMap();
            CreateMap<DepositoDto, Deposito>().ReverseMap();
            CreateMap<DetalleCajaDto, DetalleCaja>().ReverseMap();
            CreateMap<DetalleComprobanteDto, DetalleComprobante>().ReverseMap();
            CreateMap<EmpresaDto, Empresa>().ReverseMap();
            CreateMap<EmpleadoDto, Empleado>().ReverseMap();
            CreateMap<FormaPagoDto, FormaPago>().ReverseMap();
            CreateMap<GastoDto, Gasto>().ReverseMap();
            CreateMap<JornalDto, Jornal>().ReverseMap();
            CreateMap<ObraEmpleadoDto, ObraEmpleado>().ReverseMap();
            CreateMap<JornalMaterialDto, JornalMaterial>().ReverseMap();
            CreateMap<IngresoMaterialDto, IngresoMaterial>().ReverseMap();
            CreateMap<MaterialDto, Material>().ReverseMap();
            CreateMap<MovimientoDto, Movimiento>().ReverseMap();
            CreateMap<ObraDto, Obra>().ReverseMap();
            CreateMap<OperacionDto, Operacion>().ReverseMap();
            CreateMap<ProveedorDto, Proveedor>().ReverseMap();
            CreateMap<PrecioDto, Precio>().ReverseMap();
            CreateMap<PresupuestoDto, Presupuesto>().ReverseMap();
            CreateMap<RubroDto, Rubro>().ReverseMap();
            CreateMap<SalarioMinimoDto, SalarioMinimo>().ReverseMap();
            CreateMap<SalidaMaterialDto, SalidaMaterial>().ReverseMap();
            CreateMap<StockDto, Stock>().ReverseMap();
            CreateMap<SubRubroDto, SubRubro>().ReverseMap();
            CreateMap<TareaDto, Tarea>().ReverseMap();
            CreateMap<TransferenciaDto, Transferencia>().ReverseMap();
            CreateMap<TipoGastoDto, TipoGasto>().ReverseMap();
            CreateMap<UsuarioDto, Usuario>().ReverseMap();
            CreateMap<ZonaDto, Zona>().ReverseMap();
        }
    }
}
