using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiObra.Models;
using AutoMapper;
using GestionObra.Dominio.Entidades;
using GestionObra.Interfaces.AsistenciaContratista.DTOs;
using GestionObra.Interfaces.AsistenciaDiaria.DTOs;
using GestionObra.Interfaces.Banco.DTOs;
using GestionObra.Interfaces.Caja.DTOs;
using GestionObra.Interfaces.Categoria.DTOs;
using GestionObra.Interfaces.Causa.DTOs;
using GestionObra.Interfaces.ChequeEntrada.DTOs;
using GestionObra.Interfaces.ChequeSalida.DTOs;
using GestionObra.Interfaces.ComprobanteCompra.DTOs;
using GestionObra.Interfaces.ComprobanteEntrada.DTOs;
using GestionObra.Interfaces.ComprobanteSalida.DTOs;
using GestionObra.Interfaces.CondicionIva.DTOs;
using GestionObra.Interfaces.Contratista.DTOs;
using GestionObra.Interfaces.CuentaCorriente.DTOs;
using GestionObra.Interfaces.Deposito.DTOs;
using GestionObra.Interfaces.DescripcionTarea.DTOs;
using GestionObra.Interfaces.DetalleCaja.DTOs;
using GestionObra.Interfaces.DetalleComprobante.DTOs;
using GestionObra.Interfaces.Empleado.DTOs;
using GestionObra.Interfaces.Empresa.DTOs;
using GestionObra.Interfaces.FormaPago.DTOs;
using GestionObra.Interfaces.Gasto.DTOs;
using GestionObra.Interfaces.Identificacion.DTOs;
using GestionObra.Interfaces.IngresoMaterial.DTOs;
using GestionObra.Interfaces.Jornal.DTOs;
using GestionObra.Interfaces.Material.DTOs;
using GestionObra.Interfaces.Movimiento.DTOs;
using GestionObra.Interfaces.Obra.DTOs;
using GestionObra.Interfaces.Operacion.DTOs;
using GestionObra.Interfaces.Precio.DTOs;
using GestionObra.Interfaces.Presupuesto.DTOs;
using GestionObra.Interfaces.Proveedor.DTOs;
using GestionObra.Interfaces.Rubro.DTOs;
using GestionObra.Interfaces.SalarioMinimo.DTOs;
using GestionObra.Interfaces.SalidaMaterial.DTOs;
using GestionObra.Interfaces.Stock.DTOs;
using GestionObra.Interfaces.SubRubro.DTOs;
using GestionObra.Interfaces.Tarea.DTOs;
using GestionObra.Interfaces.TipoGasto.DTOs;
using GestionObra.Interfaces.Transferencia.DTOs;
using GestionObra.Interfaces.Usuario.DTOs;
using GestionObra.Interfaces.Zona.DTOs;

namespace ApiObra.AutoMapper
{
    public class MapperProfile : Profile
    {
        public MapperProfile()
        {
            CreateMap<AsistenciaContratistaDto, AsistenciaContratistaModel>().ReverseMap();
            CreateMap<AsistenciaDiariaDto, AsistenciaDiariaModel>().ReverseMap();
            CreateMap<BancoDto, BancoModel>().ReverseMap();
            CreateMap<CausaFaltaDto, CausaFaltaModel>().ReverseMap();
            CreateMap<CajaDto, CajaModel>().ReverseMap();
            CreateMap<CategoriaDto, CategoriaModel>().ReverseMap();
            CreateMap<ContratistaDto, ContratistaModel>().ReverseMap();
            CreateMap<ChequeEntradaDto, ChequeEntradaModel>().ReverseMap();
            CreateMap<ChequeSalidaDto, ChequeSalidaModel>().ReverseMap();
            CreateMap<ComprobanteCompraDto, ComprobanteCompraModel>().ReverseMap();
            CreateMap<ComprobanteEntradaDto, ComprobanteEntradaModel>().ReverseMap();
            CreateMap<ComprobanteSalidaDto, ComprobanteSalidaModel>().ReverseMap();
            CreateMap<CondicionIvaDto, CondicionIvaModel>().ReverseMap();
            CreateMap<CuentaCorrienteDto, CuentaCorrienteModel>().ReverseMap();
            CreateMap<DepositoDto, DepositoModel>().ReverseMap();
            CreateMap<DescripcionTareaDto, DescripcionTareaModel>().ReverseMap();
            CreateMap<IdentificacionDto, IdentificacionModel>().ReverseMap();
            CreateMap<DetalleCajaDto, DetalleCajaModel>().ReverseMap();
            CreateMap<DetalleComprobanteDto, DetalleComprobanteModel>().ReverseMap();
            CreateMap<EmpleadoDto, EmpleadoModel>().ReverseMap();
            CreateMap<EmpresaDto, EmpresaModel>().ReverseMap();
            CreateMap<FormaPagoDto, FormaPagoModel>().ReverseMap();
            CreateMap<GastoDto, GastoModel>().ReverseMap();
            CreateMap<JornalDto, JornalModel>().ReverseMap();
            CreateMap<ObraEmpleadoDto, JornalEmpleadoModel>().ReverseMap();
            CreateMap<JornalMaterialDto, JornalMaterialModel>().ReverseMap();
            CreateMap<IngresoMaterialDto, IngresoMaterialModel>().ReverseMap();
            CreateMap<MaterialDto, MaterialModel>().ReverseMap();
            CreateMap<MovimientoDto, MovimientoModel>().ReverseMap();
            CreateMap<OperacionDto, OperacionModel>().ReverseMap();
            CreateMap<ObraDto, ObraModel>().ReverseMap();
            CreateMap<ProveedorDto, ProveedorModel>().ReverseMap();
            CreateMap<PrecioDto, PrecioModel>().ReverseMap();
            CreateMap<PresupuestoDto, PresupuestoModel>().ReverseMap();
            CreateMap<RubroDto, RubroModel>().ReverseMap();
            CreateMap<SalarioMinimoDto , SalarioMinimoModel>().ReverseMap();
            CreateMap<SalidaMaterialDto, SalidaMaterialModel>().ReverseMap();
            CreateMap<StockDto, StockModel>().ReverseMap();
            CreateMap<SubRubroDto, SubRubroModel>().ReverseMap();
            CreateMap<TareaDto, TareaModel>().ReverseMap();
            CreateMap<TransferenciaDto, TransferenciaModel>().ReverseMap();
            CreateMap<TipoGastoDto, TipoGastoModel>().ReverseMap();
            CreateMap<UsuarioDto, UsuarioModel>().ReverseMap();
            CreateMap<ZonaDto, ZonaModel>().ReverseMap();
        }
    }
}
